# Generated by Django 2.1.2 on 2018-12-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.IntegerField()),
                ('singlerooms', models.CharField(choices=[('1', 'ONE'), ('2', 'TW0'), ('3', 'THREE')], default='1', max_length=6)),
                ('singlerooms_attached', models.CharField(choices=[('1', 'ONE'), ('2', 'TW0'), ('3', 'THREE')], default='1', max_length=6)),
                ('doublerooms', models.CharField(choices=[('1', 'ONE'), ('2', 'TW0'), ('3', 'THREE')], default='1', max_length=6)),
                ('doublerooms_attached', models.CharField(choices=[('1', 'ONE'), ('2', 'TW0'), ('3', 'THREE')], default='1', max_length=6)),
                ('triplerooms', models.CharField(choices=[('1', 'ONE'), ('2', 'TW0'), ('3', 'THREE')], default='1', max_length=6)),
                ('triplerooms_attached', models.CharField(choices=[('1', 'ONE'), ('2', 'TW0'), ('3', 'THREE')], default='1', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload')),
            ],
        ),
    ]
