# Generated by Django 2.1.2 on 2018-12-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_pages2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='pr',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
