# Generated by Django 2.1.2 on 2018-12-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('am_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenities', models.CharField(max_length=100)),
                ('pictures', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('single_a', models.IntegerField(null=True)),
                ('single_wa', models.IntegerField(null=True)),
                ('double_a', models.IntegerField(null=True)),
                ('double_wa', models.IntegerField(null=True)),
                ('triple_a', models.IntegerField(null=True)),
                ('triple_wa', models.IntegerField(null=True)),
                ('four_a', models.IntegerField(null=True)),
                ('four_wa', models.IntegerField(null=True)),
                ('price_paid', models.IntegerField()),
                ('Rating', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('Feedback', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('single_a', models.IntegerField(null=True)),
                ('single_wa', models.IntegerField(null=True)),
                ('double_a', models.IntegerField(null=True)),
                ('double_wa', models.IntegerField(null=True)),
                ('triple_a', models.IntegerField(null=True)),
                ('triple_wa', models.IntegerField(null=True)),
                ('floorbed', models.IntegerField(default=0)),
                ('price_paid', models.IntegerField()),
                ('Rating', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('Feedback', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_a', models.IntegerField()),
                ('single_wa', models.IntegerField()),
                ('double_a', models.IntegerField()),
                ('double_wa', models.IntegerField()),
                ('triple_a', models.IntegerField()),
                ('triple_wa', models.IntegerField()),
                ('four_a', models.IntegerField()),
                ('four_wa', models.IntegerField()),
                ('avg_rating', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('gallery', models.URLField(null=True)),
                ('amenities', models.ManyToManyField(to='hostupload.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_a', models.IntegerField()),
                ('single_wa', models.IntegerField()),
                ('double_a', models.IntegerField()),
                ('double_wa', models.IntegerField()),
                ('triple_a', models.IntegerField()),
                ('triple_wa', models.IntegerField()),
                ('floorbed', models.IntegerField()),
                ('avg_rating', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('guest', models.IntegerField(null=True)),
                ('amenities', models.ManyToManyField(to='hostupload.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_a', models.IntegerField()),
                ('single_wa', models.IntegerField()),
                ('double_a', models.IntegerField()),
                ('double_wa', models.IntegerField()),
                ('triple_a', models.IntegerField()),
                ('triple_wa', models.IntegerField()),
                ('four_a', models.IntegerField()),
                ('four_wa', models.IntegerField()),
                ('cleaning', models.IntegerField()),
                ('security', models.IntegerField()),
                ('cab', models.IntegerField()),
                ('food', models.IntegerField()),
                ('extra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_a', models.IntegerField()),
                ('single_wa', models.IntegerField()),
                ('double_a', models.IntegerField()),
                ('double_wa', models.IntegerField()),
                ('triple_a', models.IntegerField()),
                ('triple_wa', models.IntegerField()),
                ('floorbed', models.IntegerField()),
                ('cleaning', models.IntegerField()),
                ('security', models.IntegerField()),
                ('extra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_type', models.CharField(choices=[('1', 'Hostel'), ('2', 'House'), ('3', 'Appartment')], max_length=10)),
                ('shareable', models.BooleanField()),
                ('pr_is_personal', models.BooleanField()),
                ('for_business', models.BooleanField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pricing_house',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='pricing_hostel',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='house',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Pricing_House'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Pricing_Hostel'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='booking_house',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='booking_house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking_hostel',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload'),
        ),
        migrations.AddField(
            model_name='booking_hostel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
