# Generated by Django 2.1.2 on 2018-12-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostupload.Property_Upload')),
            ],
        ),
    ]
